language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install mountainlab_pytools pynwb==1.2.1 pyopenephys kbucket h5py MEArec exdir ruamel.yaml nixio shybrid
- pip install .
- pip install pytest==3.6
script: pytest
deploy:
  provider: pypi
  user: colehurwitz
  on:
    tags: true
  password:
    secure: Z4tufrjCuDqyOQNAC9pQGXnfVb9/QnkOV4kKBTpBdIO/CoJUN31BkfgHxtDiwvukiwYqQrA2Uv97XltpootvNDjzHw/rK55T8p1BT9YDqQ1NvNFBiqDB+tDEAXuu3396YmWmtyWR7MS346aiJ9lAXUbZnaLe7kj4IxaF0v4uF1niWwP0Ub0cjmzAatLrtOlbZfr61dQ7mRNWDKVUuRDkKRpDq8bb4g8/OBA4PaRPlcqXcpN9OtN2rnlf7XjHXhb3BozOB4TI/URh2bTCGf/1iVujjXBPmWpi15nNLeErgRaQEK2cyrkXpkRmLOzKuLa/I2irooia5ZCWG1DNC6fP8DbJ/tTroKZSk0pr+MLEbOnRR8RyLMj3ZHWXiIc2x5JkbVX/FY8CS0LyAv03UyOzszAli3vEBj22RLO0+z0170fN7FwWNTvFXCIfFoHug5lcLhTXBfLJAurlbWn4RT4jxODVgHgr5/7Km1ddz7eQ7sTvq4x8M0EavR6LKFw7V+XglB3WOhg4bOTZYZOZyw7VxOsIffti4xqnMLbq/Ze/pFIYOWoEduVitgKlRk1D+lBBbWFgmDIEnrBuTOYdDqRL3UojPhldqd8Bktjdtx22H6FGipIJwLTq4n7qy04T+ANpOJ71HI/rJCD+FE+VjxPHJBtZcyPKbvlFk1f0Tq8Y/LI=
